version: "2"

services:
    client:
        container_name: nginx-screenclip-net
        image: nginx
        ports:
            - ${HOST_PORT}:80
        volumes:
            - ${APPDATA_PATH}/nginx-nginx-screenclip-net:/usr/share/nginx/html
        restart: unless-stopped
