version: "2"
services:
    client:
        container_name: nginx-jaaax-net
        image: nginx
        ports:
            - ${HOST_PORT}:80
        volumes:
            - ${APPDATA_PATH}/nginx-jaaax-net:/usr/share/nginx/html
