version: "2"

services:
    client:
        container_name: nginx-thejeremybecker-com
        image: nginx
        ports:
            - ${HOST_PORT}:80
        volumes:
            - ${APPDATA_PATH}/nginx-thejeremybecker-com:/usr/share/nginx/html
        restart: unless-stopped
